# Generated by Django 4.0.2 on 2022-08-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'حساب', 'verbose_name_plural': 'حساب ها'},
        ),
    ]
