# Generated by Django 4.0.2 on 2023-08-04 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=500, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('status', models.CharField(choices=[('ava', 'available'), ('not', 'not_available')], default='ava', max_length=3, verbose_name='status')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime_created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime_modified')),
            ],
        ),
    ]
