# Generated by Django 4.0.2 on 2023-08-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='stars',
            field=models.CharField(blank=True, choices=[('1', 'very Bad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Perfect')], max_length=10, null=True, verbose_name='star'),
        ),
    ]
