# Generated by Django 4.0.2 on 2023-08-08 20:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_comments_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
    ]
