# Generated by Django 4.0.2 on 2022-08-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_comments_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
