# Generated by Django 4.0.2 on 2022-08-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_comments_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='recommend',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
