# Generated by Django 4.0.2 on 2022-08-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_comments_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='recommend',
            field=models.BooleanField(default=True),
        ),
    ]
