# Generated by Django 4.0.2 on 2022-08-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_comments_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='recommend',
            field=models.BooleanField(default=True, verbose_name='I suggest this product'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='stars',
            field=models.CharField(blank=True, choices=[('1', 'Very Bad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Perfect')], max_length=10, null=True, verbose_name='What is your star?'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(verbose_name='Comment Text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
