# Generated by Django 4.0.2 on 2022-08-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_category_alter_product_slug_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='products.Category', verbose_name='category'),
        ),
    ]
