# Generated by Django 4.0.2 on 2022-08-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_comments_is_active_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='child', to='products.Category', verbose_name='parent'),
        ),
    ]
