# Generated by Django 4.0.2 on 2022-08-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_category_parent_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='datetime_created'),
        ),
        migrations.AddField(
            model_name='category',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='datetime_modified'),
        ),
    ]
