# Generated by Django 4.0.2 on 2022-08-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_category_datetime_created_category_datetime_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
