# Generated by Django 4.0.2 on 2022-09-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_ipaddress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
