# Generated by Django 4.0.2 on 2022-09-10 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='datetime_created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime_created'),
        ),
    ]
